### ISSUE TITLE
Publish on CRAN?

### ISSUE THREAD

**Issue by TMiguelT** [abnormally-distributed/cvreg#2]
It would be great if this were directly installable from CRAN. There is a chance that I will need to add it as a dependency for one of my own packages. I'm not sure if that's possible from GitHub (?).

**Comment by abnormally-distributed** [comment]
the package is far too incomplete to be submitted to cran. theres lots of
documentation an bug fixes id have to do first. this is/was sort of a
personal project that I come back to as I feel like
